# Generated by Django 4.1.5 on 2023-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/thumbnail_placeholder.png', null=True, upload_to='images'),
        ),
    ]
